# Generated by Django 4.2.30 on 2026-04-10 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicGridPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='Academics & Curriculum', max_length=200, verbose_name='Section Title')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FacilityGridPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='Our Facilities', max_length=200, verbose_name='Section Title')),
                ('tagline', models.TextField(blank=True, default='Modern infrastructure for holistic learning', verbose_name='Tagline')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SchoolStatsPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Section Title')),
                ('stat1_label', models.CharField(default='Students', max_length=100, verbose_name='Stat 1 Label')),
                ('stat1_value', models.CharField(default='400+', max_length=50, verbose_name='Stat 1 Value')),
                ('stat2_label', models.CharField(default='Result', max_length=100, verbose_name='Stat 2 Label')),
                ('stat2_value', models.CharField(default='100%', max_length=50, verbose_name='Stat 2 Value')),
                ('stat3_label', models.CharField(default='Teachers', max_length=100, verbose_name='Stat 3 Label')),
                ('stat3_value', models.CharField(default='25+', max_length=50, verbose_name='Stat 3 Value')),
                ('stat4_label', models.CharField(default='Experience', max_length=100, verbose_name='Stat 4 Label')),
                ('stat4_value', models.CharField(default='75+', max_length=50, verbose_name='Stat 4 Value')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='StaffGridPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='Our Expert Faculty', max_length=200, verbose_name='Section Title')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
