# Generated by Django 4.2.30 on 2026-04-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_academicgridpluginmodel_facilitygridpluginmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicgridpluginmodel',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Section Title'),
        ),
        migrations.AlterField(
            model_name='facilitygridpluginmodel',
            name='tagline',
            field=models.TextField(blank=True, verbose_name='Tagline'),
        ),
        migrations.AlterField(
            model_name='facilitygridpluginmodel',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Section Title'),
        ),
        migrations.AlterField(
            model_name='schoolstatspluginmodel',
            name='stat1_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stat 1 Label'),
        ),
        migrations.AlterField(
            model_name='schoolstatspluginmodel',
            name='stat1_value',
            field=models.CharField(blank=True, max_length=50, verbose_name='Stat 1 Value'),
        ),
        migrations.AlterField(
            model_name='schoolstatspluginmodel',
            name='stat2_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stat 2 Label'),
        ),
        migrations.AlterField(
            model_name='schoolstatspluginmodel',
            name='stat2_value',
            field=models.CharField(blank=True, max_length=50, verbose_name='Stat 2 Value'),
        ),
        migrations.AlterField(
            model_name='schoolstatspluginmodel',
            name='stat3_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stat 3 Label'),
        ),
        migrations.AlterField(
            model_name='schoolstatspluginmodel',
            name='stat3_value',
            field=models.CharField(blank=True, max_length=50, verbose_name='Stat 3 Value'),
        ),
        migrations.AlterField(
            model_name='schoolstatspluginmodel',
            name='stat4_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stat 4 Label'),
        ),
        migrations.AlterField(
            model_name='schoolstatspluginmodel',
            name='stat4_value',
            field=models.CharField(blank=True, max_length=50, verbose_name='Stat 4 Value'),
        ),
        migrations.AlterField(
            model_name='staffgridpluginmodel',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Section Title'),
        ),
    ]
