# Generated by Django 4.2.30 on 2026-04-10 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('school', '0003_alter_academicgridpluginmodel_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicItemPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(help_text='e.g. Standard 9 & 10', max_length=100, verbose_name='Block Heading')),
                ('tag', models.CharField(default='09', help_text='Small badge text', max_length=10, verbose_name='Side Tag')),
                ('subjects', models.TextField(help_text='Enter subjects, one per line', verbose_name='Subjects List')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
