# Generated by Django 4.2.30 on 2026-04-10 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('school', '0004_academicitempluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBuilderModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('background_color', models.CharField(default='#0F172A', max_length=20, verbose_name='Background Color')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FooterColumnModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=100, verbose_name='Column Title')),
                ('body', models.TextField(help_text='Enter text or raw links', verbose_name='Column Body / Links')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HeaderSlideModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='Background Image')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('subtitle', models.TextField(blank=True, verbose_name='Subtitle')),
                ('btn_text', models.CharField(blank=True, max_length=50, verbose_name='Button Text')),
                ('btn_url', models.CharField(blank=True, max_length=200, verbose_name='Button URL')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='PremiumHeaderPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TestimonialCarouselModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Section Title')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TestimonialItemModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('author', models.CharField(max_length=100, verbose_name='Author Name')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Role (e.g. Parent)')),
                ('quote', models.TextField(verbose_name='Quote')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Photo')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
