# Generated by Django 4.2.30 on 2026-04-10 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('school', '0005_footerbuildermodel_footercolumnmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionBannerPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('subtitle', models.TextField(blank=True, verbose_name='Subtitle')),
                ('btn_text', models.CharField(max_length=50, verbose_name='Button Text')),
                ('btn_url', models.CharField(default='/admissions', max_length=200, verbose_name='Button URL')),
                ('bg_color', models.CharField(default='#F59E0B', max_length=20, verbose_name='Background Hex Color')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FacilityItemPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=200, verbose_name='Facility Title')),
                ('icon_class', models.CharField(default='🏫', max_length=50, verbose_name='Icon Class / Emoji')),
                ('image', models.ImageField(blank=True, null=True, upload_to='facilities/', verbose_name='Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='GalleryItemPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Gallery Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='StaffItemPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('designation', models.CharField(max_length=200, verbose_name='Designation')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/', verbose_name='Photo')),
                ('bio', models.TextField(blank=True, verbose_name='Brief Bio')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
