# Generated by Django 4.2.30 on 2026-04-10 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('school', '0006_admissionbannerpluginmodel_facilityitempluginmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItemPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=200, verbose_name='News Title')),
                ('date', models.DateField(verbose_name='Post Date')),
                ('excerpt', models.TextField(blank=True, verbose_name='Excerpt')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Image')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='Link URL')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterModelOptions(
            name='academicsubject',
            options={'ordering': ['standard', 'order']},
        ),
        migrations.AlterModelOptions(
            name='academicsubjecttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'academic subject Translation'},
        ),
        migrations.AlterModelOptions(
            name='admissioninfo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='admissioninfotranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'admission info Translation'},
        ),
        migrations.RemoveField(
            model_name='admissioninfotranslation',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='admissioninfotranslation',
            name='process',
        ),
        migrations.AlterField(
            model_name='academicitempluginmodel',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Block Heading'),
        ),
        migrations.AlterField(
            model_name='academicitempluginmodel',
            name='subjects',
            field=models.TextField(verbose_name='Subjects List'),
        ),
        migrations.AlterField(
            model_name='academicitempluginmodel',
            name='tag',
            field=models.CharField(default='09', max_length=10, verbose_name='Side Tag'),
        ),
        migrations.AlterField(
            model_name='academicsubject',
            name='is_optional',
            field=models.BooleanField(default=False, verbose_name='Optional'),
        ),
        migrations.AlterField(
            model_name='academicsubject',
            name='standard',
            field=models.CharField(max_length=5, verbose_name='Standard'),
        ),
        migrations.AlterField(
            model_name='admissionbannerpluginmodel',
            name='bg_color',
            field=models.CharField(default='#0F172A', max_length=20, verbose_name='Background Hex Color'),
        ),
        migrations.AlterField(
            model_name='admissioninfo',
            name='academic_year',
            field=models.CharField(default='2026-27', max_length=20, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='admissioninfo',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Open'),
        ),
        migrations.AlterField(
            model_name='admissioninfo',
            name='standard',
            field=models.CharField(max_length=5, unique=True, verbose_name='Standard'),
        ),
        migrations.AlterField(
            model_name='admissioninfotranslation',
            name='eligibility',
            field=models.TextField(verbose_name='Eligibility'),
        ),
        migrations.AlterField(
            model_name='admissioninfotranslation',
            name='fees_details',
            field=models.TextField(verbose_name='Fees'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='icon',
            field=models.CharField(default='🏫', max_length=50, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='school.gallerycategory'),
        ),
        migrations.AlterField(
            model_name='schoolstatspluginmodel',
            name='stat1_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='Label 1'),
        ),
        migrations.AlterField(
            model_name='schoolstatspluginmodel',
            name='stat1_value',
            field=models.CharField(blank=True, max_length=50, verbose_name='Value 1'),
        ),
        migrations.AlterField(
            model_name='schoolstatspluginmodel',
            name='stat2_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='Label 2'),
        ),
        migrations.AlterField(
            model_name='schoolstatspluginmodel',
            name='stat2_value',
            field=models.CharField(blank=True, max_length=50, verbose_name='Value 2'),
        ),
        migrations.AlterField(
            model_name='schoolstatspluginmodel',
            name='stat3_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='Label 3'),
        ),
        migrations.AlterField(
            model_name='schoolstatspluginmodel',
            name='stat3_value',
            field=models.CharField(blank=True, max_length=50, verbose_name='Value 3'),
        ),
        migrations.AlterField(
            model_name='schoolstatspluginmodel',
            name='stat4_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='Label 4'),
        ),
        migrations.AlterField(
            model_name='schoolstatspluginmodel',
            name='stat4_value',
            field=models.CharField(blank=True, max_length=50, verbose_name='Value 4'),
        ),
        migrations.AlterField(
            model_name='testimonialitemmodel',
            name='role',
            field=models.CharField(blank=True, max_length=100, verbose_name='Role'),
        ),
    ]
