# Generated by Django 4.2.30 on 2026-04-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_newsitempluginmodel_alter_academicsubject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumheaderpluginmodel',
            name='logo_text',
            field=models.CharField(blank=True, default='Shri Ambika', help_text='Text displayed next to the logo.', max_length=100, verbose_name='Logo Text'),
        ),
    ]
